fixtures:
  repositories:
    apt: 
      repo: 'git://github.com/puppetlabs/puppetlabs-apt'
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    collectd: "https://github.com/Yuav/puppet-collectd.git"
    yum: 
      repo: "https://github.com/voxpupuli/puppet-yum"
      ref: "0.10.0"
  forge_modules:
    refacter: "yuav/refacter"
    sensu: 
      repo: "sensu/sensu"
      ref: '2.1.0'
  symlinks:
    monitoring: "#{source_dir}"
